import React, { useEffect, useState } from 'react';
import { Card, FormField, Loader } from '../components'; // Importing Card, FormField, and Loader components

// Component to render cards based on data
const RenderCards = ({ data, title }) => {
  // If data exists and is not empty, map over it and render Card component for each item
  if (data?.length > 0) {
    return (
      data.map((post) => <Card key={post._id} {...post} />)
    );
  }

  // If no data, render a message with the provided title
  return (
    <h2 className="mt-5 font-bold text-[#6469ff] text-xl uppercase">{title}</h2>
  );
};

// Home component
const Home = () => {
  // State variables
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState('');
  const [searchTimeout, setSearchTimeout] = useState(null);
  const [searchedResults, setSearchedResults] = useState(null);

  // Function to fetch posts from the server
  const fetchPosts = async () => {
    setLoading(true);

    try {
      const response = await fetch('http://localhost:8080/api/v1/post', {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      });

      if (response.ok) {
        const result = await response.json();
        setAllPosts(result.data.reverse()); // Reverse the order of posts for display
      }
    } catch (err) {
      alert(err);
    } finally {
      setLoading(false);
    }
  };

  // useEffect hook to fetch posts when the component mounts
  useEffect(() => {
    fetchPosts();
  }, []);

  // Function to handle search input change
  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout); // Clear previous timeout
    setSearchText(e.target.value); // Update search text

    // Set a timeout to perform search after 500 milliseconds to reduce frequent searches
    setSearchTimeout(
      setTimeout(() => {
        // Filter posts based on search text (name or prompt)
        const searchResult = allPosts.filter((item) => item.name.toLowerCase().includes(searchText.toLowerCase()) || item.prompt.toLowerCase().includes(searchText.toLowerCase()));
        setSearchedResults(searchResult); // Update search results
      }, 500),
    );
  };

  // Rendering JSX
  return (
    <section className="max-w-7xl mx-auto">
      <div>
        {/* Title and description */}
        <h1 className="font-extrabold text-[#222328] text-[32px]">The Community Showcase</h1>
        <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
      </div>

      {/* Search form */}
      <div className="mt-16">
        <FormField
          labelName="Search posts"
          type="text"
          name="text"
          placeholder="Search something..."
          value={searchText}
          handleChange={handleSearchChange}
        />
      </div>

      {/* Displaying loading spinner or post cards */}
      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && ( // If search text exists, show search results title
              <h2 className="font-medium text-[#666e75] text-xl mb-3">
                Showing Results for <span className="text-[#222328]">{searchText}</span>:
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {/* RenderCards component to display cards based on search results or all posts */}
              {searchText ? (
                <RenderCards
                  data={searchedResults}
                  title="No Search Results Found"
                />
              ) : (
                <RenderCards
                  data={allPosts}
                  title="No Posts Yet"
                />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home; // Exporting Home component
